/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_GeXTN6Nsu",
    "aws_user_pools_web_client_id": "574s8a00ddh6kh03jlos1bb4c7",
    "oauth": {}
};


export default awsmobile;
